# Site setings
name: 'Ben Laplanche'
description: 'Ben is a Product Leader, Coach, Coffee Drinker & Purveyor of Puns, based in London UK'
meta_description: "Ben is a Product Leader, Coach, Coffee Drinker & Purveyor of Puns, based in London UK"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://ben.laplanche.co.uk 
disqus: 
mailchimp_url: 
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: UA-141192246-1 


# Author
author:
  name: 'Ben Laplanche'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "Ben is a Product Leader, Coach, Coffee Drinker & Purveyor of Puns, based in London UK."
  bio: "I'm enthusiastic about all things related to product management, design thinking and being customer centric. I'm currently working for Pivotal and based in London, UK."

# Contact form setings
email: ben+inboundcontact@laplanche.co.uk
contact_page_description: "If you're interested in discussing one of the services that I offer, or would just like to ask a question then please get in touch! I'd love to hear from y'all"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'ben_laplanche'
github: 'benlaplanche'
linkedin: 'ben-laplanche-6b227527'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Coaching
    url: /coaching/
  - text: Mentoring
    url: /mentoring/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
